#!/bin/zsh

umask 0002

typeset -U path
path=(~/bin ~/local/bin /usr/local/bin /var/lib/gems/1.8/bin $path)

export EDITOR=vim
export REPORTTIME=5
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'

if [ $(uname) = 'Darwin' ]; then
  # OS X helper binary
  export JAVA_HOME=`/usr/libexec/java_home`
fi

if [ -n DISPLAY ]; then
  export DISPLAY=:0.0
fi

__which() {
    /usr/bin/which $1 >/dev/null 2>&1
}
