#!/bin/zsh

# global
DOTS="..."
for ((NUM=2; NUM<=10; NUM+=1)); do
#    alias -g "..$NUM"=`..n $NUM`
    alias -g $DOTS=`..n $NUM`
    DOTS="$DOTS."
done

#alias -g '...'='..1'
#alias -g '....'='..2'
#alias -g '.....'='..3'

# ls
if [ $(uname) = 'Darwin' ]; then
  if __which gls; then
    alias ls='gls -aF --color'
  else
    echo_warn "On Darwin and 'gls' not found"
    alias ls='ls -aGp'
  fi
else
  alias ls='ls -aF --color=auto'
fi

alias ll='ls -alh'

# List only directories and symbolic
# links that point to directories
alias lsd='ls -d *(-/DN)'
alias lld='ls -ldh *(-/DN)'

# List only file beginning with "."
alias lsa='ls -d .*'
alias lla='ls -ldh .*'

# From #zsh IRC
# [1:16pm] aguynamedben: I'm new to zsh, I have a globbing alias lsr='ls -d **/*(.)', how do I get it to ALSO recursively list the contents of hidden directories?  Right now it only seems to be listing the contest no non-hidden dirs
# [1:16pm] Mikachu: (.D)
# [1:17pm] aguynamedben: ahhh that makes sense, was looking at something similar
# [1:17pm] aguynamedben: thanks, now just need to tell it not .git haha
# [1:18pm] Mikachu: **/^.git(.D) maybe
# [1:18pm] Mikachu: but that might still match things inside .git
# [1:18pm] aguynamedben: okay, I'll read more of the docs too, thanks Mikachu
# [1:19pm] Mikachu: maybe something like **/*~(*/)#.git/*(.D)
# [1:20pm] aguynamedben: you, sir, are money
# [1:20pm] aguynamedben: that seems to work
# [1:20pm] aguynamedben: the first one still caught .git stuff
# [1:20pm] Mikachu: right
# [1:20pm] aguynamedben: now to understand how you came up with that so I can learn zsh better 
# [1:21pm] Mikachu: heh
# [1:22pm] Mikachu: actually maybe (^.git/)#*(.D) would work too
# [1:23pm] aguynamedben: Mikachu: yeah that works too
# [1:23pm] Mikachu: that may or may not follow more symlinks though
# [1:23pm] aguynamedben: cool, thanks man this is so rad

alias lsr='ls -d **/*~(*/)#.git/*(.D)'
alias llr='ls -ldh **/*~(*/)#.git/*(.D)'

alias lsdr='ls -d **/*(/)'
alias lldr='ls -ldh **/*(/)'

# Standard stuff
alias mv='nocorrect mv'       # no spelling correction on mv
alias cp='nocorrect cp'       # no spelling correction on cp
alias mkdir='nocorrect mkdir' # no spelling correction on mkdir

alias j=jobs
alias pu=pushd
alias po=popd
alias d='dirs -v'
alias h=history

# application overrides
# alias grep=egrep
alias vi=vim
alias hgrep='history | grep'
alias hegrep='history | egrep'

if [ $(uname) = 'Darwin' ]; then
  if __which mvim; then
    alias vim='mvim -v'
    EDITOR='mvim -v'
  fi
fi

alias sudovim=sudo\ vim
alias sudovi=sudovim
alias suvi=sudovim

alias dud='du -ksh ./* | sort -n'

autoload zmv
# Easy "mass move" alias
alias mmv='noglob zmv -W'

# http://www.jukie.net/bart/blog/screen-ssh-agent
_ssh_auth_save() {
    mkdir -p "$HOME/.screen"
    ln -sf "$SSH_AUTH_SOCK" "$HOME/.screen/ssh-auth-sock.$HOST"
}
alias screen='_ssh_auth_save && HOST="$HOST" screen'
